### ISSUE TITLE
Test Amazon S3 as a file system

### ISSUE THREAD

**Issue by petterik** [splunk/splunk-shuttl#53]
Need someone to test if the archiver can be run with Amazon S3. Here's how it should be possible: http://wiki.apache.org/hadoop/AmazonS3

@antonjn, are you up for it?

**Comment by petterik** [comment]
Cannot use s3 yet, because of how bucketsize works at the moment.
The problem is that we're trying to read the size from the file on the remote file system. Instead, we need to get that file, and delete it later with s3. I will think about doing another abstraction, or just change the algorithm for getting size.

Stacktrace for the future:
java.lang.RuntimeException: java.io.FileNotFoundException: s3n://<ID>:<SECRET>@<BUCKET>/shuttl-archiving-manual-test/archive_data/cluster_name/server_name/archiver-test-index/db_1346803199_1346803187_1/UNKNOWN/archive_meta/bucket.size
    at com.splunk.shuttl.archiver.bucketsize.BucketSizeIO.getInputStreamToFile(BucketSizeIO.java:114)
    at com.splunk.shuttl.archiver.bucketsize.BucketSizeIO.readSizeFromRemoteFile(BucketSizeIO.java:105)
    at com.splunk.shuttl.archiver.bucketsize.ArchiveBucketSize.getSize(ArchiveBucketSize.java:59)
    at com.splunk.shuttl.archiver.thaw.BucketSizeResolver.createBucketWithSize(BucketSizeResolver.java:53)
    at com.splunk.shuttl.archiver.thaw.BucketSizeResolver.resolveBucketSize(BucketSizeResolver.java:49)
    at com.splunk.shuttl.server.mbeans.rest.ListBucketsEndpoint.getBucketWithSize(ListBucketsEndpoint.java:125)
    at com.splunk.shuttl.server.mbeans.rest.ListBucketsEndpoint.listBucketsForIndex(ListBucketsEndpoint.java:98)

**Comment by borischen** [comment]
if we cannot get bucket size, can we just leave as NA and keep going?

As long as data can go back and forth, that's sufficient. We can doc this as a limitation of S3.

**Comment by petterik** [comment]
As I was looking at my old comment, I see: "UNKNOWN", which means that the format it was searching for was unknown.
I don't know why this is, and I'm not sure what I had in my repository at the time, but everything is working as expected now.
I will however make an issue for making the bucketsize better. I've thought about it and I know of a very good solution.
