### ISSUE TITLE
Unable to use AWS S3

### ISSUE THREAD

**Issue by msnelling** [splunk/splunk-shuttl#86]
This is probably not the right place to ask this question but I'm having real problems getting Hadoop to work with S3.
I've created a bucket, set the permissions and verified the access keys work. However Hadoop failes to start with the following error in the datanode log.

I've added the following properties into both _core-site.xml_ and _hdfs-site.xml_

``` xml
<property>
  <name>fs.default.name</name>
  <value>s3://bucket-splunk-frozen</value>
</property>

<property>
  <name>fs.s3.awsAccessKeyId</name>
  <value>ID</value>
</property>

<property>
  <name>fs.s3.awsSecretAccessKey</name>
  <value>SECRET</value>
</property>
```

```
2012-09-26 14:45:32,950 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: STARTUP_MSG:
/************************************************************
STARTUP_MSG: Starting DataNode
STARTUP_MSG:   host = ubuntu/127.0.1.1
STARTUP_MSG:   args = []
STARTUP_MSG:   version = 1.0.3
STARTUP_MSG:   build = https://svn.apache.org/repos/asf/hadoop/common/branches/branch-1.0 -r 1335192; compiled by 'hortonfo' on Tue May  8 20:31:25 UTC 2012
************************************************************/
2012-09-26 14:45:33,113 INFO org.apache.hadoop.metrics2.impl.MetricsConfig: loaded properties from hadoop-metrics2.properties
2012-09-26 14:45:33,123 INFO org.apache.hadoop.metrics2.impl.MetricsSourceAdapter: MBean for source MetricsSystem,sub=Stats registered.
2012-09-26 14:45:33,124 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled snapshot period at 10 second(s).
2012-09-26 14:45:33,124 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: DataNode metrics system started
2012-09-26 14:45:33,210 INFO org.apache.hadoop.metrics2.impl.MetricsSourceAdapter: MBean for source ugi registered.
2012-09-26 14:45:33,383 ERROR org.apache.hadoop.hdfs.server.datanode.DataNode: java.net.UnknownHostException: unknown host: bucket-splunk-frozen
        at org.apache.hadoop.ipc.Client$Connection.<init>(Client.java:214)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1196)
        at org.apache.hadoop.ipc.Client.call(Client.java:1050)
        at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
        at $Proxy5.getProtocolVersion(Unknown Source)
        at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:396)
        at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:370)
        at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:429)
        at org.apache.hadoop.ipc.RPC.waitForProxy(RPC.java:331)
        at org.apache.hadoop.ipc.RPC.waitForProxy(RPC.java:296)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.startDataNode(DataNode.java:356)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.<init>(DataNode.java:299)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.makeInstance(DataNode.java:1582)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.instantiateDataNode(DataNode.java:1521)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.createDataNode(DataNode.java:1539)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.secureMain(DataNode.java:1665)
        at org.apache.hadoop.hdfs.server.datanode.DataNode.main(DataNode.java:1682)

2012-09-26 14:45:33,383 INFO org.apache.hadoop.hdfs.server.datanode.DataNode: SHUTDOWN_MSG:
/************************************************************
SHUTDOWN_MSG: Shutting down DataNode at ubuntu/127.0.1.1
************************************************************/
```

**Comment by petterik** [comment]
I'm sorry, but I can't help you with that.

But if you're trying to Shuttl with s3, there's an easier way:
Configure your `<archiverRootURI>` to be `s3://<ID>:<SECRET>@<BUCKET>/archiving_root` and you should be all set.
You can use s3n as well.
